### ISSUE TITLE
LAN server crashes after a number of seconds.

### ISSUE THREAD

**Issue by selfAndrewKB** [jweigelt/swbf2admin#55]
```[5/28/2022 8:11:17 AM] WARN  | Server has crashed.
[5/28/2022 8:11:17 AM] INFO  | Automatic restart is enabled. Restarting server...
[5/28/2022 8:11:17 AM] INFO  | Launching server with args '/win /norender /nosound /autonet dedicated /resolution 640 480'
[5/28/2022 8:11:17 AM] INFO  | Connected to rcon server at '192.168.1.77:3658'. Sending login...
[5/28/2022 8:11:17 AM] INFO  | Login OK. Rcon ready.
[5/28/2022 8:11:57 AM] WARN  | Rcon disconnected. System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at SWBF2Admin.Runtime.Rcon.RconClient.WorkThread_Run()```

Ad infinitum. When the server is set to WAN everything appears to activate just fine, Unfortunately it seems just about no one else has talked about this issue anywhere else so it's very tough to troubleshoot with just google this time around.

LIkely the same as #54 but that didn't include any information and I fear it has fallen through the cracks.

**Comment by kingzy21** [comment]
[24/03/2023 13:10:18] WARN  | Rcon disconnected. System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at SWBF2Admin.Runtime.Rcon.RconClient.WorkThread_Run()
[24/03/2023 13:10:18] WARN  | Server has crashed.

I have exactly the same error here. It's only when LAN is selected or LAN is set to 1 in the ServerSettings.cfg

Going to try and narrow this down. Could possibly be linked to GoG being selected as the server i willl try with gamespy and steam and see if this makes any difference. Also tried selecting different network ip to see if this would help but it looks to be an exception only presented when using the LAN option.

**Comment by Wil1Killa** [comment]
The steam/gog version does not have working LAN dedicated servers. It broke in the update
